webtalk_init -webtalk_dir /home/ugur/Desktop/lab_02/lab_02.sim/sim_1/behav/xsim/xsim.dir/TestBench02_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Oct 20 17:34:42 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "ffc80134-c554-4e8c-b155-9f42f00f8909" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "41aee19ce0e546c2af7a45bb5f1fa813" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "LinuxMint" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Linux Mint 19.2 Tina" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Celeron(R) CPU 1000M @ 1.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1795.776 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "4.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.22_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "125624_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1938911698 -regid "" -xml /home/ugur/Desktop/lab_02/lab_02.sim/sim_1/behav/xsim/xsim.dir/TestBench02_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/ugur/Desktop/lab_02/lab_02.sim/sim_1/behav/xsim/xsim.dir/TestBench02_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/ugur/Desktop/lab_02/lab_02.sim/sim_1/behav/xsim/xsim.dir/TestBench02_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
